### ISSUE TITLE
Tom and Jerry in House Trap player 1 only working if "dualshock" is selected in core options. And similar issue with Silhouette Mirage

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#297]
Hello!

It seems to have a problem with Tom and Jerry in House Trap and controls, when "standard" is selected in core options you can navigate menus, etc. but once you select "single player" and it goes ingame the controller doesnt respond anymore!

You have to set type to "dualshock" to be able to move/pause/etc.

In 2 players mode 2nd player works fine with "standard", 1st player still needs to be set to "dualshock".

Latest version of the core (2945189 when I type this) on Windows 10 and and Linux (tested on a VM and on SNES Classic).

**Comment by bslenul** [comment]
Oh and kinda similar issue with Silhouette Mirage, controller seems to be recognized at launch because you can skip the first logo, but once in the main menu no controls!

You have to switch to "dualshock" and then it works, you can even switch back to "standard" if you want but it will only work until next loading it seems.

**Comment by Sakitoshi** [comment]
In the case of silhouette mirage, in the localization process they modified the game to require a dualshock controller. So working as intended.
Don't know if it would be the same for tom and jerry.

**Comment by bslenul** [comment]
>In the case of silhouette mirage, in the localization process they modified the game to require a dualshock controller. So working as intended.

Any source for that? Seems weird since it works perfectly fine in Beetle PSX without DualShock + it wouldnt work at all after switching back to normal controller if it was only compatible with DualShock.

**Comment by bslenul** [comment]
Both games fixed with #468, they now work properly with "standard" controller 👍

**Comment by negativeExponent** [comment]
thats great to hear. Legend of Mana is also one that annoys me for awhile, sadly that game's fmv audio is still broken. haven't played on it yet to know if there are any audio parts that audio is nor working well.
