### ISSUE TITLE
Disney's Donald Duck: Quack Attack (PAL): cutscenes are ended abruptly

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#778]
As in the title the cutscenes in the game are ended abruptly. (To reproduce just start a new game, the first cutscene will load and will end automatically after a couple of seconds).

**Comment by pcercuei** [comment]
I can't reproduce, maybe it was fixed recently? Can you try again?

**Comment by CometHunter92** [comment]
It still happens, tried with the latest commit, arm32 and arm64. The dump is ok, it works correctly with other cores.

**Comment by pcercuei** [comment]
Ok, strange. I had that problem at some point, and it disappeared overnight. Now it works fine here (on PC and GameCube).

**Comment by CometHunter92** [comment]
PC and GC use lightrec, right? Here it happens with the dynarec disabled too,

**Comment by notaz** [comment]
I can't reproduce this, maybe it got fixed by something already?

**Comment by CometHunter92** [comment]
Still happens at the latest commit. I need to verify my dump, but on other emulators works as intended.

**Comment by pcercuei** [comment]
> Still happens at the latest commit. I need to verify my dump, but on other emulators works as intended.

BIOS or HLE?

**Comment by CometHunter92** [comment]
BIOS

**Comment by CometHunter92** [comment]
Oh sorry, this was driving me mad, damaged dump. Sorry
